### PR TITLE
Fix aws temporary credentials access

### PR DESCRIPTION
**Pull request by rnatarajan**
Enabled the plugin to use AWS STS Credentials for authentication using AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN

### CODE REVIEW

**Comment by ohhatiya** [comment]
The [EnvironmentVariableCredentialsProvider](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/EnvironmentVariableCredentialsProvider.java), which is part of the DefaultCredentialsProviderChain, should read these variables already.

**Comment by rnatarajan** [comment]
Thanks, Shall use the EnvironmentVariableCredentialsProvider(part of DefaultCredentialsProviderChain) way of reading the variables.
Shall Discard(Close) this pull request.

**Comment by ohhatiya** [comment]
:metal: In case it's not already clear, you can make it use the default provider chain by simply not providing credentials in the Maven configuration.

**Comment by rnatarajan** [comment]
Didnt look at EnvironmentVariableCredentialsProvider Implementation earlier. 
Saw the Implementation after your Comment.
Already working on tweaking the Maven's Configuration to ensure that the token I wanted are read !

**Comment by rnatarajan** [comment]
Reopening the Pull request.

**Comment by Pance** [comment]
rnatarajan and myself did a trace of the code to see where the session token was being loaded.

We started tracing from [this method in CreateOrUpdateS3RepoMojo](https://github.com/bazaarvoice/s3repo-maven-plugin/blob/master/src/main/java/com/bazaarvoice/maven/plugin/s3repo/create/CreateOrUpdateS3RepoMojo.java#L338). This method creates an instance of the [DefaultAWSCredentialsProviderChain class.](https://github.com/aws/aws-sdk-java/blob/1.9.1/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java#L33) 

We looked into the [javadoc](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html?tag=duckduckgo-ffcm-20) for this class and found that this credentials provider chain does not mention that it loads an AWS_SESSION_TOKEN.

We know for sure that this credentials provider chain object will not return a session token because the baseclass of DefaultAWSCredentialsProviderChain, AWSCredentialsProviderChain, [returns an object of type AWSCredentials](https://github.com/aws/aws-sdk-java/blob/1.9.1/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWSCredentialsProviderChain.java#L94). The [AWSCredentials interface](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/AWSCredentials.html) does not support returning a sessiontoken, so the object returned by DefaultCredentialsProviderChain.getCredentials() does not return a sessiontoken.

Because the DefaultAWSCredentialsProviderChain does not return a session token, we need the changes in this PR

**Comment by ohhatiya** [comment]
Hmmm. It's not properly documented, but if you look at the source it does read the AWS_SESSION_TOKEN variable. If it's present, it instead returns a [AWSSessionCredentials](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWSSessionCredentials.java) object. The signature implentations ([v4](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L179) and [v3](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS3Signer.java#L90)) both check to see if they receive an object of that type, and if so use it to create the request signature.

So it *should* work. That said, I haven't checked the specific clients the plugin uses to verify they use those signers.

**Comment by Pance** [comment]
I understand that EnvironmentVariableCredentialsProvider reads the session token variable from the environment. The problem that I am seeing is that this session token variable is not returned by the DefaultCredentialsProviderChain object.

We are invoking this maven plugin from jenkins, where we are putting the access_key, secret_key and session_token variables into the environment. Whenever jenkins tries to execute this maven plugin task, it throws an 'Access Denied' error. However, if jenkins uses the aws cli to list or put files into the target bucket then there are no 'access denied' errors. When the aws cli is used by jenkins, all of the AWS keys (including the session token) are picked up from the environment correctly. It appears to us that the maven plugin is not picking up the session token from the environment.

I don't understand where the Signer classes fit into this picture; could you explain that to me please?

**Comment by ohhatiya** [comment]
The Signer is what actually makes use of the credentials. It should see that it is given an AWSSessionCredentials object and then incorporate the session token when calculating the signature for API calls. It may be that it's not doing this properly for some reason, though.

**Comment by handavid** [comment]
The InstanceProfileCredentialsProvider is the one that creates an AWSSessionCredentials, not the EnvironmentVariableCredentialsProvider. Try not setting the environment variables at all.

**Comment by Pance** [comment]
Thanks for the information, everyone. We are going to close this and do more testing. We'll reopen it if we need to

**Comment by rnatarajan** [comment]
Closing the pull request.

**Comment by rnatarajan** [comment]
Maven Version was the culprit. Using Maven-3.1.1 and s3repo-maven-plugin version 3.5 fixed the issue.

**Pull request closed without merging**
